requirements_dev.txt

Currently the build fails due to dep mis-matches.
This change removes the specific version and allows pip to
work it out.

(maint) The locked version of the oapi dep breaks the build

---

featureflags/client.py

**What has changed**
Adds check on the variation methods for each type before we try to enqueue analytics
**Behaviour**
Currently:
with analytics as false we get an exception saying every time we poll for a flag
`AttributeError: 'CfClient' object has no attribute '_analytics'`
After change:
We do not hit the code to send analytics because it is false and won't exist

[FFM-3689]: Add Check to see if analytics are enabled before trying to enqueue them

---

featureflags/config.py
featureflags/polling.py

**What has changed**
Adds method 'with_pull_interval' - this is in line with other sdks - currently updating config and setting pull interval was not changing time
Adds minimum pull interval time of 60 seconds (this would never have been less than 60s because it was never changing before hand)
**Behaviour**
not calling with_pull_interval - defaults to 60 seconds
with_pull_interval(60 or greater) -> sets pull interval to specified time
with_pull_interval(less than 60) -> logs that pull level must be 60+ then sets pull interval to default 60s

[FFM-3685]: Add method to set poll interval, enforce minimum poll time of 60s

---

featureflags/repository.py

with the new segment, but it was comparing the version from the same object so it
always failed.
This meant that data might not be evaluted correctly until the SDK
restarts.

[SWAT-8089]: Python SDK doesnt update cache after segment change event

---

featureflags/evaluations/evaluator.py

**What**
[FFM-3868](https://harness.atlassian.net/browse/FFM-3868)
Remove type check on pre requisites check so MV Flags evaluate correctly
**Why**
When a pre req is not a boolean flag we don't evaluate correctly. This can cause behaviour where once turned on, flags with prereqs cannot be turned off, regardless of the pre req state
**Testing**
Manually tested MV and Bool scenarios, flags evaluating correctly

FFM-3667 - Remove type check on pre req check as MV flags do not evaluate correctly

---

featureflags/client.py
featureflags/polling.py
featureflags/streaming.py
tests/unit/test_evaluator.py

This change introduces a backoff retry on stream failure. It also signals that the poller should start on any stream failures, pausing the poller if the stream successfully reconnects.
Its done by sharing a threading Event between the poller and streamer so that they can signal one another.
On a stream error the SDK starts spamming the ff-server with requests as fast as it can.  This has resulted in 429 being returned to some customers.

[FFM-5352]: Stream errors cause the SDK to spam ff server requests

---

featureflags/evaluations/clause.py
featureflags/evaluations/evaluator.py
featureflags/evaluations/segment.py
tests/integration/test_evaluator.py

This change fixes an issue with the pre-req evaluations, where the evaluator was AND'ing if the variation was valid and not present.
Updated the evalutor tests to use the latest ff-test-cases

[FFM-5263]: Fix pre-req evaluations

---

featureflags/__init__.py
featureflags/analytics.py
featureflags/evaluations/auth_target.py
setup.cfg
setup.py

The SDK did not check or convert non-string attribute values to string, which resulted in 500 errors from the metrics service. This change solves that by:
1. A type check so that if any constant non-string values are provided they’ll get caught by static analysis in your IDE
2. A runtime check which converts non-string values to String.
So the SDK posts valid target data 
Tested with the following Targets. All were registered with correct attributes and flag evaluation events were registered as well.
target = Target(identifier='erdi1', attributes={"email": 123})
target2 = Target(identifier='erdi2', attributes={"email": {"hello": "hello"}})
target3 = Target(identifier='erdi3', attributes={"email": [123, "123", True, {"Hello": 123}, {"Hello": "123"}]})
target4 = Target(identifier='erdi4', …

FFM-6158 Convert non-string attribute values to string

---

featureflags/evaluations/auth_target.py

Changing attributes type from any to string didn't make sense, as we accept non-string values. This will remove the warning if users use non-string attribute values.

FFM-6158 Remove static check

---

featureflags/ftypes/string.py
tests/unit/test_string.py

The `in` operator was lower casing the values to be compared. All operators are case sensitive apart from `equals_insensitive` so this change removes that behaviour.
TestGrid
- Failing scenarios now passing
- No regression on other scenarios
Unit tests updated

FFM-5991 Make IN operator case sensitive

---

featureflags/__init__.py
featureflags/evaluations/evaluator.py
setup.cfg
setup.py

Error in logic would cause the prerequisite loop to return early. This fix allows multiple prerequisites and any nested prerequisites to be checked.
Testgrid + manual:
- all testgrid scenarios passing  
- nested prerequisites evaluating correctly in manual check

FFM-6410 Evaluate multiple and nested prerequisites correctly

---

featureflags/__init__.py
featureflags/sse_client.py
setup.cfg
setup.py

When iterating through a new stream event, we catch three different exceptions. The `StopIteration` exception and `EOFError` have a `value` of `None` which results in an empty string when being logged, resulting in unhelpful error logs. This change adds type checks and logs more approriate statements depending on the error type. 
To remove blank log statements. 
Simulated `StopIteration` errors using the `mocklb` tool in ff-server. I was unable to simulate `EOFError` so just to be on the safe side, I have not logged its value, but tailored a log string for it.

FFM-7880 Improve SSE Client error logging

---

featureflags/evaluations/variation.py

The SDK already logged a message if it failed evaluation and had to return the default variation in https://github.com/harness/ff-python-server-sdk/pull/58 - this PR appends the correct SDK code to the log message
Manual - all public xVariation funtions

FFM-5496 Add SDK Code to failed evaluation 

---

docs/further_reading.md
featureflags/__init__.py
featureflags/api/client.py
featureflags/api/default/authenticate.py
featureflags/client.py
featureflags/config.py

The SDK did not have a retry mechanism for "retryable" HTTP errors when authenticating. It also had unhandled exceptions in these cases and the SDK would crash. 
This PR adds 
1. Retry mechanism for certain HTTP codes with logging which adheres to the SDK codes wiki. Adds a new optional config option `with_max_auth_retries` with the default being 10 if not specified.
3. If authentication fails: 
- then the SDK will not start any other post-authentication services like polling or streaming. 
- The SDK will only serve default values with log messaging adhering to SDK codes wiki
No unit tests exist for the API layer at all, so instead of taking another day or two to create them, I performed manual testing
1. Happy path - SDK gets 200.
2. Retryable error path - SDK retries on correct codes …

FFM-7177 Authentication Retries

---

featureflags/__init__.py
setup.cfg
setup.py

What
The previous release 1.1.13 has been deleted from Pypi due to it being broken. Pypi does not let you override a release, so while I have deleted 1.1.13 from Pypi, I need to publish a new version with the fix.

1.1.14 release prep

---

featureflags/__init__.py
featureflags/analytics.py
featureflags/api/client.py
featureflags/sdk_logging_codes.py
setup.cfg
setup.py
tests/unit/test_sdk_logging_codes.py

This is a temporary solution for FFM-8231. We are seeing `read_timeout` errors in the SDK for metrics requests. This is due to huge numbers of targets being sent in the metrics payload. see a breakdown of response times:
20k target: 8 seconds
50K targets: 18 seconds
55K targets: 28 seconds
This PR addresses the number of Targets that we can send to the metrics service in each metrics interval. If we use 30 seconds as the maximum time we allow SDKs to wait on a response for a metrics request, then that limit is reached if we send 60K targets. To prevent read_timeouts, this PR increases the `read_timeout` to 30 seconds and sets the Target limit to 50000 which should process and yield a `200` response in 18 seconds, which gives as 12 second margin of error.
The SDK will log code `7004` if …

FFM-8231 Temporary limit of TargetMetrics size

---

featureflags/__init__.py
featureflags/analytics.py
featureflags/polling.py
featureflags/sdk_logging_codes.py
featureflags/sse_client.py
featureflags/streaming.py
setup.cfg
setup.py
tests/unit/test_sdk_logging_codes.py

- Removes the responsiblity for logging streaming errors from the `sse_client` module to the `streaming` module. 
- Logs a warning if the SDK is still connecting after four attempts.
The sse_client catches iteration errors and potential empty chunk errors, which will happen frequently for any transitive network issues. We were previously logging these as errors which was misleading. 
Manual disconnect/reconnect

FFM-8544 Reorganise streaming logs

---

featureflags/analytics.py

See issue: https://github.com/harness/ff-python-server-sdk/issues/95 
`Unset` is a type that is defined differently between Open API generated code.  In this case, the type from the metrics code was being used to check if for target attributes.  This caused errors to be logged as the actual `Unset` type was from the config code.  This PR uses the correct type to stop errors being logged. 
- Manual with sample app: supplied target with no attributes. 
- TestGrid

FFM-11655 Fix typing for target attributes in metrics

---

featureflags/streaming.py

**What**
- Adds a None check on the feature config type before we attempt to log it
**Why**
- If the featureConfig is None then we'll get an error

PL-51773 Add guard around debug log

---

requirements_dev.txt

Bumps setuptools to ~=70.0.0
CVE ID
CVE-2024-6345
*This is a dev dependency and is not shipped to user code*

MAINT Patch setuptools CVE

---

featureflags/client.py
featureflags/config.py

Does what it says on the tin.
Adds a `httpx_args` dict to `Config`, and a `with_httpx_args()` helper, which if specified multiple times will update the set of existing arguments. This is passed to the `Client` and `AuthenticatedClient` constructors.
Use case - using a HTTP proxy, e.g. `httpx_args={'proxy': 'http://my-proxy:8080'}`.

{client,config}: allow passing through additional httpx arguments

---

featureflags/lru_cache.py

**Changes**
Increase default size of LRUCache.
Log a warning if an item is evicted from the cache

fix: [FFM-12288]: bump lru cache default size

---

featureflags/evaluations/evaluator.py
featureflags/ftypes/boolean.py
featureflags/ftypes/utils.py
tests/unit/test_boolean.py
tests/unit/test_integer.py
tests/unit/test_number.py

**Changes**
- Correctly cast string to boolean when attempting to evaluate a boolean equals clause e.g. target has attribute `premium: True` and we're attempting to check if that target belongs to a group with a rule of `premium equals true`
- Handle errors casting values. Previously if a target had an attribute of type `integer/number/whatever` we would assume the matching target group attribute could be successfully cast to this type, failure to do so would result in a runtime error. Added error handling to log and continue if this issue occurs in future.

fix: [FFM-12349]: fix bool equals clause
